### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by therealssj** [SkycoinProject/multicoin-wallet#3]
Using skycoin's wallet structure for coin wallets

Skycoin Wallet API: https://github.com/SkycoinProject/skycoin/blob/develop/src/wallet/wallet.go#L488
https://github.com/SkycoinProject/skycoin/blob/develop/src/api/gateway.go#L100

Note: skycoin wallet code already has partial support for btc as they are very similar ( https://github.com/skycoinproject/skycoin/wiki/Technical-background-of-version-0-Skycoin-addresses )

**Development Tasks**

- [x] Use common interface for handling address entries
       Currently some functions use `cipher.Address` as input/output this should be replaced by a common interface for addresses

- [x] Add ETH Wallet handling
       The existing code only supports skycoin and bitcoin ( partially )

**Comment by therealssj** [comment]
#2 finished

**Comment by jdknives** [comment]
Fixed by #2
